// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.SchoolDepartment.Infra.DataStruct.Data.Contexts;

#nullable disable

namespace Project.SchoolDepartment.Infra.DataStruct.Data.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Project.SchoolDepartment.Infra.DataStruct.Data.Entities.Aluno", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("VARCHAR(80)");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("CHAR(11)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("VARCHAR(60)");

                    b.Property<Guid>("CursoGuid")
                        .HasColumnType("char(36)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("VARCHAR(9)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("VARCHAR(160)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("VARCHAR(60)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("RA")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("CHAR(80)");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR(120)");

                    b.Property<Guid>("TurmaGuid")
                        .HasColumnType("char(36)");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("CHAR(2)");

                    b.HasKey("Guid");

                    b.HasIndex("CPF")
                        .IsUnique();

                    b.HasIndex("CursoGuid");

                    b.HasIndex("RA")
                        .IsUnique();

                    b.HasIndex("TurmaGuid");

                    b.ToTable("Aluno");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("c70c3bce-c77a-428a-b8c1-28174b6e0ba6"),
                            Bairro = "Bairro Qualquer",
                            CPF = "11111111111",
                            Cidade = "Cidade Qualquer",
                            CursoGuid = new Guid("a69dda80-aed1-452a-afa7-5c09d4885ba1"),
                            Genero = "Masculino",
                            Logradouro = "Rua Aleatória",
                            Nome = "Eduardo",
                            Numero = 278,
                            RA = "FLF7BWJEFIUDR9EDQUUCDB6EUKFE8WKHG7ZZKH6GLQ9DUAJPX5B3AXUWWYEFHB9KLZ5CLO1WF5YLEF8I",
                            Sobrenome = "Oliveira da Silva",
                            TurmaGuid = new Guid("43b26e0f-93e9-46ca-a574-c5e0b78c7a3b"),
                            UF = "SP"
                        });
                });

            modelBuilder.Entity("Project.SchoolDepartment.Infra.DataStruct.Data.Entities.Curso", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("VARCHAR(180)");

                    b.HasKey("Guid");

                    b.ToTable("Curso");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("a69dda80-aed1-452a-afa7-5c09d4885ba1"),
                            Nome = "Ciência da Computação"
                        });
                });

            modelBuilder.Entity("Project.SchoolDepartment.Infra.DataStruct.Data.Entities.Telefone", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AlunoGuid")
                        .HasColumnType("char(36)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("VARCHAR(11)");

                    b.HasKey("Guid");

                    b.HasIndex("AlunoGuid");

                    b.ToTable("Telefone");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("67a0c359-dd38-4527-9393-db3a311ad0b4"),
                            AlunoGuid = new Guid("c70c3bce-c77a-428a-b8c1-28174b6e0ba6"),
                            Numero = "99999999999"
                        },
                        new
                        {
                            Guid = new Guid("c93a8a36-bf0b-411d-a11a-10f65493562a"),
                            AlunoGuid = new Guid("c70c3bce-c77a-428a-b8c1-28174b6e0ba6"),
                            Numero = "88888888888"
                        });
                });

            modelBuilder.Entity("Project.SchoolDepartment.Infra.DataStruct.Data.Entities.Turma", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CursoGuid")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("VARCHAR(5)");

                    b.Property<int>("QuantidadeAlunos")
                        .HasColumnType("int");

                    b.HasKey("Guid");

                    b.HasIndex("CursoGuid");

                    b.ToTable("Turma");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("43b26e0f-93e9-46ca-a574-c5e0b78c7a3b"),
                            CursoGuid = new Guid("a69dda80-aed1-452a-afa7-5c09d4885ba1"),
                            DataFim = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInicio = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Periodo = "Manha",
                            QuantidadeAlunos = 1
                        });
                });

            modelBuilder.Entity("Project.SchoolDepartment.Infra.DataStruct.Data.Entities.Aluno", b =>
                {
                    b.HasOne("Project.SchoolDepartment.Infra.DataStruct.Data.Entities.Curso", "Curso")
                        .WithMany("Alunos")
                        .HasForeignKey("CursoGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.SchoolDepartment.Infra.DataStruct.Data.Entities.Turma", "Turma")
                        .WithMany("Alunos")
                        .HasForeignKey("TurmaGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("Project.SchoolDepartment.Infra.DataStruct.Data.Entities.Telefone", b =>
                {
                    b.HasOne("Project.SchoolDepartment.Infra.DataStruct.Data.Entities.Aluno", "Aluno")
                        .WithMany("Telefones")
                        .HasForeignKey("AlunoGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("Project.SchoolDepartment.Infra.DataStruct.Data.Entities.Turma", b =>
                {
                    b.HasOne("Project.SchoolDepartment.Infra.DataStruct.Data.Entities.Curso", "Curso")
                        .WithMany("Turmas")
                        .HasForeignKey("CursoGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("Project.SchoolDepartment.Infra.DataStruct.Data.Entities.Aluno", b =>
                {
                    b.Navigation("Telefones");
                });

            modelBuilder.Entity("Project.SchoolDepartment.Infra.DataStruct.Data.Entities.Curso", b =>
                {
                    b.Navigation("Alunos");

                    b.Navigation("Turmas");
                });

            modelBuilder.Entity("Project.SchoolDepartment.Infra.DataStruct.Data.Entities.Turma", b =>
                {
                    b.Navigation("Alunos");
                });
#pragma warning restore 612, 618
        }
    }
}
